#!/usr/bin/env node
/**
 * Session End Hook
 * Logs session information to .opencode/sessions/ for review
 */

import { writeTextFile, getOpenCodeDir, getTimestamp } from "../lib/utils.js";
import { join } from "path";

const run = async () => {
  try {
    const timestamp = getTimestamp();
    const sessionFile = join(getOpenCodeDir(), "sessions", `${timestamp}.md`);

    // Get git info if available
    let gitBranch = "unknown";
    let gitStatus = "";
    try {
      const { exec } = await import("child_process");
      const { promisify } = await import("util");
      const execAsync = promisify(exec);
      
      const branchResult = await execAsync("git branch --show-current");
      gitBranch = branchResult.stdout.trim() || "unknown";
      
      const statusResult = await execAsync("git status --short");
      gitStatus = statusResult.stdout.trim();
    } catch {
      // Git not available or not in a repo
    }

    const log = `# Session Log

**Date:** ${new Date().toLocaleString("es-ES", { 
  timeZone: "Europe/Madrid",
  dateStyle: "full",
  timeStyle: "medium"
})}

**Project:** MSI-a
**Branch:** ${gitBranch}

## Git Status
\`\`\`
${gitStatus || "No changes or git not available"}
\`\`\`

## Session Notes
Session ended automatically. Review this log for:
- Files modified during session
- Patterns to extract into skills
- Context optimization opportunities

---
*Generated by MSI-a OpenCode hooks*
`;

    await writeTextFile(sessionFile, log);
    console.log(`[Hook] Session logged to ${sessionFile}`);
  } catch (error) {
    console.error(`[Hook] Failed to log session: ${error.message}`);
  }
};

run();
